"""initial schema: jobs and master profile

Revision ID: 2682ca1c3796
Revises: 
Create Date: 2026-06-15 10:56:04.058642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2682ca1c3796'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'MATCHED', 'REJECTED_BY_AI', name='job_status'), server_default='NEW', nullable=False),
    # ``sa.func.now()`` compiles per-dialect (CURRENT_TIMESTAMP on SQLite,
    # now() on PostgreSQL). A literal ``sa.text('now()')`` would emit Postgres-
    # only SQL and break inserts on the SQLite dev database.
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_postings'))
    )
    op.create_index(op.f('ix_job_postings_status'), 'job_postings', ['status'], unique=False)
    op.create_table('master_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('target_titles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_profiles'))
    )
    op.create_table('profile_experiences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('highlights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['master_profiles.id'], name=op.f('fk_profile_experiences_profile_id_master_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_experiences'))
    )
    op.create_index(op.f('ix_profile_experiences_profile_id'), 'profile_experiences', ['profile_id'], unique=False)
    op.create_table('profile_skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['master_profiles.id'], name=op.f('fk_profile_skills_profile_id_master_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_skills'))
    )
    op.create_index(op.f('ix_profile_skills_profile_id'), 'profile_skills', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_skills_profile_id'), table_name='profile_skills')
    op.drop_table('profile_skills')
    op.drop_index(op.f('ix_profile_experiences_profile_id'), table_name='profile_experiences')
    op.drop_table('profile_experiences')
    op.drop_table('master_profiles')
    op.drop_index(op.f('ix_job_postings_status'), table_name='job_postings')
    op.drop_table('job_postings')
    # ### end Alembic commands ###
