"""add_company_website

Revision ID: 2f488d1e25ad
Revises: a8b6c7d8e9f0
Create Date: 2026-06-17 16:52:15.742460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f488d1e25ad'
down_revision: Union[str, Sequence[str], None] = 'a8b6c7d8e9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('company_website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'company_website')
    # ### end Alembic commands ###
