"""add_recruiter_contact

Revision ID: 777c6c8d6179
Revises: 2f488d1e25ad
Create Date: 2026-06-18 09:23:40.260642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777c6c8d6179'
down_revision: Union[str, Sequence[str], None] = '2f488d1e25ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('recruiter_name', sa.String(length=255), nullable=True))
    op.add_column('job_postings', sa.Column('recruiter_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'recruiter_email')
    op.drop_column('job_postings', 'recruiter_name')
    # ### end Alembic commands ###
